-- MySQL Script generated by MySQL Workbench
-- 07/25/17 13:35:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aerolinea
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aerolinea` ;

-- -----------------------------------------------------
-- Schema aerolinea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aerolinea` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `aerolinea` ;

-- -----------------------------------------------------
-- Table `aerolinea`.`Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Personal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Personal` (
  `idPersonal` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Documento` ENUM('C.C', 'T.I', 'C.E', 'R.C', 'Otros') NOT NULL,
  `Documento` BIGINT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Apellido` VARCHAR(60) NOT NULL,
  `Telefono` BIGINT NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  `Correo` VARCHAR(60) NOT NULL,
  `Cargo` ENUM('Piloto', 'Copiloto', 'Auxiliar', 'Ingeniero_Vuelo', 'Azafata') NOT NULL,
  `Rh` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersonal`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Documento_UNIQUE` ON `aerolinea`.`Personal` (`Documento` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Aerolinea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Aerolinea` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Aerolinea` (
  `idAerolinea` INT NOT NULL AUTO_INCREMENT,
  `Razon_Social` VARCHAR(60) NOT NULL,
  `Nit` INT NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  `Correo` VARCHAR(60) NOT NULL,
  `Telefono` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAerolinea`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Avion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Avion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Avion` (
  `idAvion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `Modelo` VARCHAR(60) NOT NULL,
  `Tiempo_Vuelo` INT NOT NULL,
  `Capacidad_Silla` INT(3) NOT NULL,
  `Asiento_Negocios_Fin` INT NOT NULL,
  `Aerolinea_idAerolinea` INT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo', 'Destinado') NOT NULL,
  PRIMARY KEY (`idAvion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Departamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Departamentos` (
  `idDepartamentos` INT NOT NULL AUTO_INCREMENT,
  `Departamentos` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartamentos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Ciudades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Ciudades` (
  `idCiudades` INT NOT NULL AUTO_INCREMENT,
  `Ciudad` VARCHAR(60) NOT NULL,
  `Departamentos_idDepartamentos` INT NOT NULL,
  PRIMARY KEY (`idCiudades`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Rutas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Rutas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Rutas` (
  `idRutas` INT NOT NULL AUTO_INCREMENT,
  `Origen` INT NOT NULL,
  `Destino` INT NOT NULL,
  `Duracion` INT NOT NULL,
  `Precio_Negocios` INT NOT NULL,
  `Precio_Economico` INT NOT NULL,
  `Estado` ENUM('Activa', 'Inactiva') NOT NULL,
  PRIMARY KEY (`idRutas`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Vuelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Vuelo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Vuelo` (
  `idVuelo` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Tipo` ENUM('Ida', 'Ida-Vuelta') NOT NULL,
  `Avion_idAvion` INT NOT NULL,
  `Rutas_idRutas` INT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo', 'Realizado') NOT NULL,
  PRIMARY KEY (`idVuelo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Combo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Combo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Combo` (
  `idCombo` INT NOT NULL AUTO_INCREMENT,
  `Ninos` INT(1) NOT NULL,
  `Adultos` INT(1) NOT NULL,
  `Fecha_Ida` DATETIME NOT NULL,
  `Fecha_Vuelta` DATETIME NOT NULL,
  `Precio` INT(9) NOT NULL,
  `Vuelo_idVuelo` INT NOT NULL,
  PRIMARY KEY (`idCombo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Pasajero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Pasajero` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Pasajero` (
  `idPasajero` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Documento` ENUM('C.C', 'T.I', 'C.E', 'R.C', 'Otros') NOT NULL,
  `Documento` BIGINT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Apellido` VARCHAR(60) NOT NULL,
  `Telefono` BIGINT NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idPasajero`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Tiquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Tiquete` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Tiquete` (
  `idTiquete` INT NOT NULL AUTO_INCREMENT,
  `Clase` ENUM('Empresarial', 'Economica') NOT NULL,
  `Numero_Asiento` INT(3) NOT NULL,
  `Valor` INT(9) NOT NULL,
  `Estado` ENUM('Activo', 'inactivo') NOT NULL,
  `Pasajero_idPasajero` INT NOT NULL,
  `Vuelo_idVuelo` INT NULL,
  `Combo_idCombo` INT NULL,
  PRIMARY KEY (`idTiquete`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Documento` VARCHAR(45) NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`Personal_has_Vuelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`Personal_has_Vuelo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`Personal_has_Vuelo` (
  `Personal_idPersonal` INT NOT NULL,
  `Vuelo_idVuelo` INT NOT NULL,
  PRIMARY KEY (`Personal_idPersonal`, `Vuelo_idVuelo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aerolinea`.`AsientosTickete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aerolinea`.`AsientosTickete` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aerolinea`.`AsientosTickete` (
  `Vuelo_idVuelo` INT NOT NULL,
  `Tiquete_idTiquete` INT NOT NULL,
  `NAsiento` INT NOT NULL,
  `Clase` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Vuelo_idVuelo`, `Tiquete_idTiquete`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
